name: Container-native c10s

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  podman_build:
    name: Podman Build c10s
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      # cargo-culted from rpm-ostree CI
      # https://github.com/containers/podman/discussions/17362
      - name: Get newer podman
        run: |
          set -xeuo pipefail
          echo 'deb [trusted=yes] https://ftp.debian.org/debian/ testing main' | sudo tee /etc/apt/sources.list.d/testing.list
          sudo apt update
          sudo apt install -y crun/testing podman/testing skopeo/testing
          # Something is confused in latest GHA here
          sudo rm /var/lib/containers -rf
      - name: Download override packages and create yum repo
        run: |
          podman run --rm -v $PWD:/run/src -w /run/src quay.io/centos/centos:stream10 sh -c '
            set -xeuo pipefail
            dnf -y install koji createrepo_c python3-dnf python3-pyyaml && dnf clean all
            overridesdir="overrides/rpm"

            # prepare directory to download override packages
            mkdir -p "${overridesdir}"

            curl -LO https://raw.githubusercontent.com/coreos/coreos-assembler/refs/heads/main/src/download-overrides.py
            python3 download-overrides.py --downloaddir "./${overridesdir}" --lockfiledir "./"

            # create local yum repo
            if [[ -n $(ls "${overridesdir}/"*.rpm 2> /dev/null) ]]; then
              (cd "${overridesdir}" && createrepo_c .)
            else
              # remove empty dir rpmoverrides
              rm -rf "${overridesdir}/"
            fi
            rm download-overrides.py
          '
      - name: Build c10s
        # Note: we should be able to drop the `-v $PWD:/run/src` once
        # https://github.com/containers/buildah/issues/5952 is fixed.
        run: |
          set -xeuo pipefail
          podman build --security-opt=label=disable --cap-add=all --device /dev/fuse --build-arg-file build-args-c10s.conf -v $PWD:/run/src . -t localhost/scos-10
      - name: Sanity-check
        run: podman run --rm localhost/scos-10 echo hello
